/********************************************************************************
** Form generated from reading UI file 'clavier_alpha.ui'
**
** Created: Tue Apr 16 09:32:41 2013
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CLAVIER_ALPHA_H
#define UI_CLAVIER_ALPHA_H

#include <Qt3Support/Q3ButtonGroup>
#include <Qt3Support/Q3GroupBox>
#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QPushButton>
#include "QtGui/QLineEdit"

QT_BEGIN_NAMESPACE

class Ui_clavier_alpha
{
public:
    Q3ButtonGroup *buttonGroup1;
    QPushButton *T4;
    QPushButton *T6;
    QPushButton *T7;
    QPushButton *T5;
    QPushButton *T8;
    QPushButton *T9;
    QPushButton *T1;
    QPushButton *T2;
    QPushButton *T0;
    QPushButton *TA;
    QPushButton *TQ;
    QPushButton *TW;
    QPushButton *T3;
    QPushButton *TZ;
    QPushButton *TT;
    QPushButton *TY;
    QPushButton *TU;
    QPushButton *TI;
    QPushButton *TO;
    QPushButton *TE;
    QPushButton *TD;
    QPushButton *TS;
    QPushButton *TR;
    QPushButton *TF;
    QPushButton *TG;
    QPushButton *TH;
    QPushButton *TJ;
    QPushButton *TK;
    QPushButton *TL;
    QPushButton *TX;
    QPushButton *TC;
    QPushButton *TV;
    QPushButton *TB;
    QPushButton *TN;
    QPushButton *Tvirgule;
    QPushButton *TPo;
    QPushButton *Tpp;
    QPushButton *TSP;
    QPushButton *TMo;
    QPushButton *TVal;
    QPushButton *TM;
    QPushButton *TCLR;
    QPushButton *TP;
    QPushButton *TBS;

    void setupUi(QDialog *clavier_alpha)
    {
        if (clavier_alpha->objectName().isEmpty())
            clavier_alpha->setObjectName(QString::fromUtf8("clavier_alpha"));
        clavier_alpha->setEnabled(true);
        clavier_alpha->resize(549, 160);
        clavier_alpha->setCursor(QCursor(Qt::PointingHandCursor));
        clavier_alpha->setFocusPolicy(Qt::NoFocus);
        clavier_alpha->setModal(true);
        buttonGroup1 = new Q3ButtonGroup(clavier_alpha);
        buttonGroup1->setObjectName(QString::fromUtf8("buttonGroup1"));
        buttonGroup1->setGeometry(QRect(2, 1, 545, 156));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(buttonGroup1->sizePolicy().hasHeightForWidth());
        buttonGroup1->setSizePolicy(sizePolicy);
        QFont font;
        font.setPointSize(22);
        buttonGroup1->setFont(font);
        buttonGroup1->setCursor(QCursor(Qt::PointingHandCursor));
        T4 = new QPushButton(buttonGroup1);
        QButtonGroup *buttonGroup = new QButtonGroup(clavier_alpha);
        buttonGroup->setObjectName(QString::fromUtf8("buttonGroup"));
        buttonGroup->addButton(T4);
        T4->setObjectName(QString::fromUtf8("T4"));
        T4->setGeometry(QRect(145, 2, 50, 40));
        sizePolicy.setHeightForWidth(T4->sizePolicy().hasHeightForWidth());
        T4->setSizePolicy(sizePolicy);
        T4->setFont(font);
        T4->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(T4, 52);
        T6 = new QPushButton(buttonGroup1);
        buttonGroup->addButton(T6);
        T6->setObjectName(QString::fromUtf8("T6"));
        T6->setGeometry(QRect(239, 2, 50, 40));
        sizePolicy.setHeightForWidth(T6->sizePolicy().hasHeightForWidth());
        T6->setSizePolicy(sizePolicy);
        T6->setFont(font);
        T6->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(T6, 54);
        T7 = new QPushButton(buttonGroup1);
        buttonGroup->addButton(T7);
        T7->setObjectName(QString::fromUtf8("T7"));
        T7->setGeometry(QRect(286, 2, 50, 40));
        sizePolicy.setHeightForWidth(T7->sizePolicy().hasHeightForWidth());
        T7->setSizePolicy(sizePolicy);
        T7->setFont(font);
        T7->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(T7, 55);
        T5 = new QPushButton(buttonGroup1);
        buttonGroup->addButton(T5);
        T5->setObjectName(QString::fromUtf8("T5"));
        T5->setGeometry(QRect(192, 2, 50, 40));
        sizePolicy.setHeightForWidth(T5->sizePolicy().hasHeightForWidth());
        T5->setSizePolicy(sizePolicy);
        T5->setFont(font);
        T5->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(T5, 53);
        T8 = new QPushButton(buttonGroup1);
        buttonGroup->addButton(T8);
        T8->setObjectName(QString::fromUtf8("T8"));
        T8->setGeometry(QRect(333, 2, 50, 40));
        sizePolicy.setHeightForWidth(T8->sizePolicy().hasHeightForWidth());
        T8->setSizePolicy(sizePolicy);
        T8->setFont(font);
        T8->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(T8, 56);
        T9 = new QPushButton(buttonGroup1);
        buttonGroup->addButton(T9);
        T9->setObjectName(QString::fromUtf8("T9"));
        T9->setGeometry(QRect(380, 2, 50, 40));
        sizePolicy.setHeightForWidth(T9->sizePolicy().hasHeightForWidth());
        T9->setSizePolicy(sizePolicy);
        T9->setFont(font);
        T9->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(T9, 57);
        T1 = new QPushButton(buttonGroup1);
        buttonGroup->addButton(T1);
        T1->setObjectName(QString::fromUtf8("T1"));
        T1->setGeometry(QRect(4, 2, 50, 40));
        sizePolicy.setHeightForWidth(T1->sizePolicy().hasHeightForWidth());
        T1->setSizePolicy(sizePolicy);
        T1->setFont(font);
        T1->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(T1, 49);
        T2 = new QPushButton(buttonGroup1);
        buttonGroup->addButton(T2);
        T2->setObjectName(QString::fromUtf8("T2"));
        T2->setGeometry(QRect(51, 2, 50, 40));
        sizePolicy.setHeightForWidth(T2->sizePolicy().hasHeightForWidth());
        T2->setSizePolicy(sizePolicy);
        T2->setFont(font);
        T2->setCursor(QCursor(Qt::PointingHandCursor));
        T2->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(T2, 50);
        T0 = new QPushButton(buttonGroup1);
        buttonGroup->addButton(T0);
        T0->setObjectName(QString::fromUtf8("T0"));
        T0->setGeometry(QRect(427, 2, 50, 40));
        sizePolicy.setHeightForWidth(T0->sizePolicy().hasHeightForWidth());
        T0->setSizePolicy(sizePolicy);
        T0->setFont(font);
        T0->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(T0, 48);
        TA = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TA);
        TA->setObjectName(QString::fromUtf8("TA"));
        TA->setGeometry(QRect(4, 39, 50, 40));
        sizePolicy.setHeightForWidth(TA->sizePolicy().hasHeightForWidth());
        TA->setSizePolicy(sizePolicy);
        TA->setFont(font);
        TA->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TA, 65);
        TQ = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TQ);
        TQ->setObjectName(QString::fromUtf8("TQ"));
        TQ->setGeometry(QRect(4, 76, 50, 40));
        sizePolicy.setHeightForWidth(TQ->sizePolicy().hasHeightForWidth());
        TQ->setSizePolicy(sizePolicy);
        TQ->setFont(font);
        TQ->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TQ, 81);
        TW = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TW);
        TW->setObjectName(QString::fromUtf8("TW"));
        TW->setGeometry(QRect(4, 113, 50, 40));
        sizePolicy.setHeightForWidth(TW->sizePolicy().hasHeightForWidth());
        TW->setSizePolicy(sizePolicy);
        TW->setFont(font);
        TW->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TW, 87);
        T3 = new QPushButton(buttonGroup1);
        buttonGroup->addButton(T3);
        T3->setObjectName(QString::fromUtf8("T3"));
        T3->setGeometry(QRect(98, 2, 50, 40));
        sizePolicy.setHeightForWidth(T3->sizePolicy().hasHeightForWidth());
        T3->setSizePolicy(sizePolicy);
        T3->setFont(font);
        T3->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(T3, 51);
        TZ = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TZ);
        TZ->setObjectName(QString::fromUtf8("TZ"));
        TZ->setGeometry(QRect(51, 39, 50, 40));
        sizePolicy.setHeightForWidth(TZ->sizePolicy().hasHeightForWidth());
        TZ->setSizePolicy(sizePolicy);
        TZ->setFont(font);
        TZ->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TZ, 90);
        TT = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TT);
        TT->setObjectName(QString::fromUtf8("TT"));
        TT->setGeometry(QRect(192, 39, 50, 40));
        sizePolicy.setHeightForWidth(TT->sizePolicy().hasHeightForWidth());
        TT->setSizePolicy(sizePolicy);
        TT->setFont(font);
        TT->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TT, 84);
        TY = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TY);
        TY->setObjectName(QString::fromUtf8("TY"));
        TY->setGeometry(QRect(239, 39, 50, 40));
        sizePolicy.setHeightForWidth(TY->sizePolicy().hasHeightForWidth());
        TY->setSizePolicy(sizePolicy);
        TY->setFont(font);
        TY->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TY, 89);
        TU = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TU);
        TU->setObjectName(QString::fromUtf8("TU"));
        TU->setGeometry(QRect(286, 39, 50, 40));
        sizePolicy.setHeightForWidth(TU->sizePolicy().hasHeightForWidth());
        TU->setSizePolicy(sizePolicy);
        TU->setFont(font);
        TU->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TU, 85);
        TI = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TI);
        TI->setObjectName(QString::fromUtf8("TI"));
        TI->setGeometry(QRect(333, 39, 50, 40));
        sizePolicy.setHeightForWidth(TI->sizePolicy().hasHeightForWidth());
        TI->setSizePolicy(sizePolicy);
        TI->setFont(font);
        TI->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TI, 73);
        TO = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TO);
        TO->setObjectName(QString::fromUtf8("TO"));
        TO->setGeometry(QRect(380, 39, 50, 40));
        sizePolicy.setHeightForWidth(TO->sizePolicy().hasHeightForWidth());
        TO->setSizePolicy(sizePolicy);
        TO->setFont(font);
        TO->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TO, 79);
        TE = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TE);
        TE->setObjectName(QString::fromUtf8("TE"));
        TE->setGeometry(QRect(98, 39, 50, 40));
        sizePolicy.setHeightForWidth(TE->sizePolicy().hasHeightForWidth());
        TE->setSizePolicy(sizePolicy);
        TE->setFont(font);
        TE->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TE, 69);
        TD = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TD);
        TD->setObjectName(QString::fromUtf8("TD"));
        TD->setGeometry(QRect(98, 76, 50, 40));
        sizePolicy.setHeightForWidth(TD->sizePolicy().hasHeightForWidth());
        TD->setSizePolicy(sizePolicy);
        TD->setFont(font);
        TD->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TD, 68);
        TS = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TS);
        TS->setObjectName(QString::fromUtf8("TS"));
        TS->setGeometry(QRect(51, 76, 50, 40));
        sizePolicy.setHeightForWidth(TS->sizePolicy().hasHeightForWidth());
        TS->setSizePolicy(sizePolicy);
        TS->setFont(font);
        TS->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TS, 83);
        TR = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TR);
        TR->setObjectName(QString::fromUtf8("TR"));
        TR->setGeometry(QRect(145, 39, 50, 40));
        sizePolicy.setHeightForWidth(TR->sizePolicy().hasHeightForWidth());
        TR->setSizePolicy(sizePolicy);
        TR->setFont(font);
        TR->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TR, 82);
        TF = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TF);
        TF->setObjectName(QString::fromUtf8("TF"));
        TF->setGeometry(QRect(145, 76, 50, 40));
        sizePolicy.setHeightForWidth(TF->sizePolicy().hasHeightForWidth());
        TF->setSizePolicy(sizePolicy);
        TF->setFont(font);
        TF->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TF, 70);
        TG = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TG);
        TG->setObjectName(QString::fromUtf8("TG"));
        TG->setGeometry(QRect(192, 76, 50, 40));
        sizePolicy.setHeightForWidth(TG->sizePolicy().hasHeightForWidth());
        TG->setSizePolicy(sizePolicy);
        TG->setFont(font);
        TG->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TG, 71);
        TH = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TH);
        TH->setObjectName(QString::fromUtf8("TH"));
        TH->setGeometry(QRect(239, 76, 50, 40));
        sizePolicy.setHeightForWidth(TH->sizePolicy().hasHeightForWidth());
        TH->setSizePolicy(sizePolicy);
        TH->setFont(font);
        TH->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TH, 72);
        TJ = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TJ);
        TJ->setObjectName(QString::fromUtf8("TJ"));
        TJ->setGeometry(QRect(286, 76, 50, 40));
        sizePolicy.setHeightForWidth(TJ->sizePolicy().hasHeightForWidth());
        TJ->setSizePolicy(sizePolicy);
        TJ->setFont(font);
        TJ->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TJ, 74);
        TK = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TK);
        TK->setObjectName(QString::fromUtf8("TK"));
        TK->setGeometry(QRect(333, 76, 50, 40));
        sizePolicy.setHeightForWidth(TK->sizePolicy().hasHeightForWidth());
        TK->setSizePolicy(sizePolicy);
        TK->setFont(font);
        TK->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TK, 75);
        TL = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TL);
        TL->setObjectName(QString::fromUtf8("TL"));
        TL->setGeometry(QRect(380, 76, 50, 40));
        sizePolicy.setHeightForWidth(TL->sizePolicy().hasHeightForWidth());
        TL->setSizePolicy(sizePolicy);
        TL->setFont(font);
        TL->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TL, 76);
        TX = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TX);
        TX->setObjectName(QString::fromUtf8("TX"));
        TX->setGeometry(QRect(51, 113, 50, 40));
        sizePolicy.setHeightForWidth(TX->sizePolicy().hasHeightForWidth());
        TX->setSizePolicy(sizePolicy);
        TX->setFont(font);
        TX->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TX, 88);
        TC = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TC);
        TC->setObjectName(QString::fromUtf8("TC"));
        TC->setGeometry(QRect(98, 113, 50, 40));
        sizePolicy.setHeightForWidth(TC->sizePolicy().hasHeightForWidth());
        TC->setSizePolicy(sizePolicy);
        TC->setFont(font);
        TC->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TC, 67);
        TV = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TV);
        TV->setObjectName(QString::fromUtf8("TV"));
        TV->setGeometry(QRect(145, 113, 50, 40));
        sizePolicy.setHeightForWidth(TV->sizePolicy().hasHeightForWidth());
        TV->setSizePolicy(sizePolicy);
        TV->setFont(font);
        TV->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TV, 86);
        TB = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TB);
        TB->setObjectName(QString::fromUtf8("TB"));
        TB->setGeometry(QRect(192, 113, 50, 40));
        sizePolicy.setHeightForWidth(TB->sizePolicy().hasHeightForWidth());
        TB->setSizePolicy(sizePolicy);
        TB->setFont(font);
        TB->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TB, 66);
        TN = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TN);
        TN->setObjectName(QString::fromUtf8("TN"));
        TN->setGeometry(QRect(239, 113, 50, 40));
        sizePolicy.setHeightForWidth(TN->sizePolicy().hasHeightForWidth());
        TN->setSizePolicy(sizePolicy);
        TN->setFont(font);
        TN->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TN, 78);
        Tvirgule = new QPushButton(buttonGroup1);
        buttonGroup->addButton(Tvirgule);
        Tvirgule->setObjectName(QString::fromUtf8("Tvirgule"));
        Tvirgule->setGeometry(QRect(286, 113, 50, 40));
        sizePolicy.setHeightForWidth(Tvirgule->sizePolicy().hasHeightForWidth());
        Tvirgule->setSizePolicy(sizePolicy);
        Tvirgule->setFont(font);
        Tvirgule->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(Tvirgule, 44);
        TPo = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TPo);
        TPo->setObjectName(QString::fromUtf8("TPo"));
        TPo->setGeometry(QRect(333, 113, 50, 40));
        sizePolicy.setHeightForWidth(TPo->sizePolicy().hasHeightForWidth());
        TPo->setSizePolicy(sizePolicy);
        QFont font1;
        font1.setPointSize(22);
        font1.setBold(true);
        font1.setWeight(75);
        TPo->setFont(font1);
        TPo->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TPo, 46);
        Tpp = new QPushButton(buttonGroup1);
        buttonGroup->addButton(Tpp);
        Tpp->setObjectName(QString::fromUtf8("Tpp"));
        Tpp->setGeometry(QRect(380, 113, 50, 40));
        sizePolicy.setHeightForWidth(Tpp->sizePolicy().hasHeightForWidth());
        Tpp->setSizePolicy(sizePolicy);
        Tpp->setFont(font);
        Tpp->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(Tpp, 58);
        TSP = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TSP);
        TSP->setObjectName(QString::fromUtf8("TSP"));
        TSP->setGeometry(QRect(480, 2, 60, 40));
        sizePolicy.setHeightForWidth(TSP->sizePolicy().hasHeightForWidth());
        TSP->setSizePolicy(sizePolicy);
        TSP->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TSP, 32);
        TMo = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TMo);
        TMo->setObjectName(QString::fromUtf8("TMo"));
        TMo->setGeometry(QRect(427, 113, 50, 40));
        sizePolicy.setHeightForWidth(TMo->sizePolicy().hasHeightForWidth());
        TMo->setSizePolicy(sizePolicy);
        TMo->setFont(font1);
        TMo->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TMo, 45);
        TVal = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TVal);
        TVal->setObjectName(QString::fromUtf8("TVal"));
        TVal->setGeometry(QRect(480, 113, 60, 40));
        TVal->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TVal, 100);
        TM = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TM);
        TM->setObjectName(QString::fromUtf8("TM"));
        TM->setGeometry(QRect(427, 76, 50, 40));
        sizePolicy.setHeightForWidth(TM->sizePolicy().hasHeightForWidth());
        TM->setSizePolicy(sizePolicy);
        TM->setFont(font);
        TM->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TM, 77);
        TCLR = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TCLR);
        TCLR->setObjectName(QString::fromUtf8("TCLR"));
        TCLR->setGeometry(QRect(480, 76, 60, 40));
        sizePolicy.setHeightForWidth(TCLR->sizePolicy().hasHeightForWidth());
        TCLR->setSizePolicy(sizePolicy);
        TCLR->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TCLR, 98);
        TP = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TP);
        TP->setObjectName(QString::fromUtf8("TP"));
        TP->setGeometry(QRect(427, 39, 50, 40));
        sizePolicy.setHeightForWidth(TP->sizePolicy().hasHeightForWidth());
        TP->setSizePolicy(sizePolicy);
        TP->setFont(font);
        TP->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TP, 80);
        TBS = new QPushButton(buttonGroup1);
        buttonGroup->addButton(TBS);
        TBS->setObjectName(QString::fromUtf8("TBS"));
        TBS->setGeometry(QRect(480, 39, 60, 40));
        sizePolicy.setHeightForWidth(TBS->sizePolicy().hasHeightForWidth());
        TBS->setSizePolicy(sizePolicy);
        TBS->setFocusPolicy(Qt::NoFocus);
        buttonGroup1->insert(TBS, 99);

        retranslateUi(clavier_alpha);
        QObject::connect(buttonGroup1, SIGNAL(clicked(int)), clavier_alpha, SLOT(buttonGroup1_clicked(int)));

        QMetaObject::connectSlotsByName(clavier_alpha);
    } // setupUi

    void retranslateUi(QDialog *clavier_alpha)
    {
        clavier_alpha->setWindowTitle(QApplication::translate("clavier_alpha", "-", 0, QApplication::UnicodeUTF8));
        buttonGroup1->setTitle(QString());
        T4->setText(QApplication::translate("clavier_alpha", "4", 0, QApplication::UnicodeUTF8));
        T4->setShortcut(QApplication::translate("clavier_alpha", "4", 0, QApplication::UnicodeUTF8));
        T6->setText(QApplication::translate("clavier_alpha", "6", 0, QApplication::UnicodeUTF8));
        T6->setShortcut(QApplication::translate("clavier_alpha", "6", 0, QApplication::UnicodeUTF8));
        T7->setText(QApplication::translate("clavier_alpha", "7", 0, QApplication::UnicodeUTF8));
        T7->setShortcut(QApplication::translate("clavier_alpha", "7", 0, QApplication::UnicodeUTF8));
        T5->setText(QApplication::translate("clavier_alpha", "5", 0, QApplication::UnicodeUTF8));
        T5->setShortcut(QApplication::translate("clavier_alpha", "5", 0, QApplication::UnicodeUTF8));
        T8->setText(QApplication::translate("clavier_alpha", "8", 0, QApplication::UnicodeUTF8));
        T8->setShortcut(QApplication::translate("clavier_alpha", "8", 0, QApplication::UnicodeUTF8));
        T9->setText(QApplication::translate("clavier_alpha", "9", 0, QApplication::UnicodeUTF8));
        T9->setShortcut(QApplication::translate("clavier_alpha", "9", 0, QApplication::UnicodeUTF8));
        T1->setText(QApplication::translate("clavier_alpha", "1", 0, QApplication::UnicodeUTF8));
        T1->setShortcut(QApplication::translate("clavier_alpha", "1", 0, QApplication::UnicodeUTF8));
        T2->setText(QApplication::translate("clavier_alpha", "2", 0, QApplication::UnicodeUTF8));
        T2->setShortcut(QApplication::translate("clavier_alpha", "2", 0, QApplication::UnicodeUTF8));
        T0->setText(QApplication::translate("clavier_alpha", "0", 0, QApplication::UnicodeUTF8));
        T0->setShortcut(QApplication::translate("clavier_alpha", "0", 0, QApplication::UnicodeUTF8));
        TA->setText(QApplication::translate("clavier_alpha", "A", 0, QApplication::UnicodeUTF8));
        TA->setShortcut(QApplication::translate("clavier_alpha", "A", 0, QApplication::UnicodeUTF8));
        TQ->setText(QApplication::translate("clavier_alpha", "Q", 0, QApplication::UnicodeUTF8));
        TQ->setShortcut(QApplication::translate("clavier_alpha", "Q", 0, QApplication::UnicodeUTF8));
        TW->setText(QApplication::translate("clavier_alpha", "W", 0, QApplication::UnicodeUTF8));
        TW->setShortcut(QApplication::translate("clavier_alpha", "W", 0, QApplication::UnicodeUTF8));
        T3->setText(QApplication::translate("clavier_alpha", "3", 0, QApplication::UnicodeUTF8));
        T3->setShortcut(QApplication::translate("clavier_alpha", "3", 0, QApplication::UnicodeUTF8));
        TZ->setText(QApplication::translate("clavier_alpha", "Z", 0, QApplication::UnicodeUTF8));
        TZ->setShortcut(QApplication::translate("clavier_alpha", "Z", 0, QApplication::UnicodeUTF8));
        TT->setText(QApplication::translate("clavier_alpha", "T", 0, QApplication::UnicodeUTF8));
        TT->setShortcut(QApplication::translate("clavier_alpha", "T", 0, QApplication::UnicodeUTF8));
        TY->setText(QApplication::translate("clavier_alpha", "Y", 0, QApplication::UnicodeUTF8));
        TY->setShortcut(QApplication::translate("clavier_alpha", "Y", 0, QApplication::UnicodeUTF8));
        TU->setText(QApplication::translate("clavier_alpha", "U", 0, QApplication::UnicodeUTF8));
        TU->setShortcut(QApplication::translate("clavier_alpha", "U", 0, QApplication::UnicodeUTF8));
        TI->setText(QApplication::translate("clavier_alpha", "I", 0, QApplication::UnicodeUTF8));
        TI->setShortcut(QApplication::translate("clavier_alpha", "I", 0, QApplication::UnicodeUTF8));
        TO->setText(QApplication::translate("clavier_alpha", "O", 0, QApplication::UnicodeUTF8));
        TO->setShortcut(QApplication::translate("clavier_alpha", "O", 0, QApplication::UnicodeUTF8));
        TE->setText(QApplication::translate("clavier_alpha", "E", 0, QApplication::UnicodeUTF8));
        TE->setShortcut(QApplication::translate("clavier_alpha", "E", 0, QApplication::UnicodeUTF8));
        TD->setText(QApplication::translate("clavier_alpha", "D", 0, QApplication::UnicodeUTF8));
        TD->setShortcut(QApplication::translate("clavier_alpha", "D", 0, QApplication::UnicodeUTF8));
        TS->setText(QApplication::translate("clavier_alpha", "S", 0, QApplication::UnicodeUTF8));
        TS->setShortcut(QApplication::translate("clavier_alpha", "S", 0, QApplication::UnicodeUTF8));
        TR->setText(QApplication::translate("clavier_alpha", "R", 0, QApplication::UnicodeUTF8));
        TR->setShortcut(QApplication::translate("clavier_alpha", "R", 0, QApplication::UnicodeUTF8));
        TF->setText(QApplication::translate("clavier_alpha", "F", 0, QApplication::UnicodeUTF8));
        TF->setShortcut(QApplication::translate("clavier_alpha", "F", 0, QApplication::UnicodeUTF8));
        TG->setText(QApplication::translate("clavier_alpha", "G", 0, QApplication::UnicodeUTF8));
        TG->setShortcut(QApplication::translate("clavier_alpha", "G", 0, QApplication::UnicodeUTF8));
        TH->setText(QApplication::translate("clavier_alpha", "H", 0, QApplication::UnicodeUTF8));
        TH->setShortcut(QApplication::translate("clavier_alpha", "H", 0, QApplication::UnicodeUTF8));
        TJ->setText(QApplication::translate("clavier_alpha", "J", 0, QApplication::UnicodeUTF8));
        TJ->setShortcut(QApplication::translate("clavier_alpha", "J", 0, QApplication::UnicodeUTF8));
        TK->setText(QApplication::translate("clavier_alpha", "K", 0, QApplication::UnicodeUTF8));
        TK->setShortcut(QApplication::translate("clavier_alpha", "K", 0, QApplication::UnicodeUTF8));
        TL->setText(QApplication::translate("clavier_alpha", "L", 0, QApplication::UnicodeUTF8));
        TL->setShortcut(QApplication::translate("clavier_alpha", "L", 0, QApplication::UnicodeUTF8));
        TX->setText(QApplication::translate("clavier_alpha", "X", 0, QApplication::UnicodeUTF8));
        TX->setShortcut(QApplication::translate("clavier_alpha", "X", 0, QApplication::UnicodeUTF8));
        TC->setText(QApplication::translate("clavier_alpha", "C", 0, QApplication::UnicodeUTF8));
        TC->setShortcut(QApplication::translate("clavier_alpha", "C", 0, QApplication::UnicodeUTF8));
        TV->setText(QApplication::translate("clavier_alpha", "V", 0, QApplication::UnicodeUTF8));
        TV->setShortcut(QApplication::translate("clavier_alpha", "V", 0, QApplication::UnicodeUTF8));
        TB->setText(QApplication::translate("clavier_alpha", "B", 0, QApplication::UnicodeUTF8));
        TB->setShortcut(QApplication::translate("clavier_alpha", "B", 0, QApplication::UnicodeUTF8));
        TN->setText(QApplication::translate("clavier_alpha", "N", 0, QApplication::UnicodeUTF8));
        TN->setShortcut(QApplication::translate("clavier_alpha", "N", 0, QApplication::UnicodeUTF8));
        Tvirgule->setText(QApplication::translate("clavier_alpha", ",", 0, QApplication::UnicodeUTF8));
        Tvirgule->setShortcut(QString());
        TPo->setText(QApplication::translate("clavier_alpha", ".", 0, QApplication::UnicodeUTF8));
        TPo->setShortcut(QApplication::translate("clavier_alpha", ".", 0, QApplication::UnicodeUTF8));
        Tpp->setText(QApplication::translate("clavier_alpha", ":", 0, QApplication::UnicodeUTF8));
        Tpp->setShortcut(QApplication::translate("clavier_alpha", ":", 0, QApplication::UnicodeUTF8));
        TSP->setText(QString());
        TSP->setShortcut(QApplication::translate("clavier_alpha", "Space", 0, QApplication::UnicodeUTF8));
        TMo->setText(QApplication::translate("clavier_alpha", "-", 0, QApplication::UnicodeUTF8));
        TMo->setShortcut(QApplication::translate("clavier_alpha", "-", 0, QApplication::UnicodeUTF8));
        TVal->setText(QString());
        TVal->setShortcut(QApplication::translate("clavier_alpha", "Return", 0, QApplication::UnicodeUTF8));
        TM->setText(QApplication::translate("clavier_alpha", "M", 0, QApplication::UnicodeUTF8));
        TM->setShortcut(QApplication::translate("clavier_alpha", "M", 0, QApplication::UnicodeUTF8));
        TCLR->setText(QString());
        TCLR->setShortcut(QApplication::translate("clavier_alpha", "Del", 0, QApplication::UnicodeUTF8));
        TP->setText(QApplication::translate("clavier_alpha", "P", 0, QApplication::UnicodeUTF8));
        TP->setShortcut(QApplication::translate("clavier_alpha", "P", 0, QApplication::UnicodeUTF8));
        TBS->setText(QString());
        TBS->setShortcut(QString());
    } // retranslateUi

};

namespace Ui {
    class clavier_alpha: public Ui_clavier_alpha {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CLAVIER_ALPHA_H
